replicaCount: 3

image:
  repository: us-central1-docker.pkg.dev/terraform-project-4132022/artemis/artemis
  tag: "7.0.0"

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  className: “nginx”
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: “0"
    ingress.kubernetes.io/ssl-redirect: “false”
    cert-manager.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-edit-in-place: “true”
  hosts:
    - host: stage-artemis.pathofneo.net
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: stage-artemis-tls
      hosts:
        - stage-artemis.pathofneo.net
